scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ["otel-collector:8888"]
      - targets: ["otel-collector:8889"]
  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']