version: '3'
services:
  guild-be:
    build:
      context: .
      dockerfile: Dockerfile
    image: guild-be-image
    container_name: build-be-container
    ports:
      - 8080:8000

  otel-collector:
    image: 'otel/opentelemetry-collector-contrib:0.88.0'
    container_name: 'otel-collector'
    restart: 'always'
    command:
      - '--config=/etc/otel-collector-config.yaml'
    volumes:
      - './config/otel-collector-config.yaml:/etc/otel-collector-config.yaml'
    ports:
      - '1888:1888'   # pprof extension
      - '8888:8888'   # Prometheus metrics exposed by the collector
      - '8889:8889'   # Prometheus exporter metrics
      - '13133:13133' # health_check extension
      - '4317:4317'   # otlp grpc

  # Prometheus
  prometheus:
    image: 'prom/prometheus:v2.47.2'
    container_name: 'prometheus'
    restart: 'always'
    command:
      - '--config.file=/etc/prometheus.yaml'
    volumes:
      - './config/prometheus.yaml:/etc/prometheus.yaml'
    ports:
      - '9090:9090'

  # Grafana
  grafana:
    image: 'grafana/grafana:10.1.1'
    container_name: 'grafana'
    restart: 'always'
    volumes:
      - ./config/grafana/provisioning/datasources/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    ports:
      - '3000:3000'
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor

  # Grafana Tempo
  tempo:
    image: 'grafana/tempo:r119-fcd31bd'
    container_name: 'tempo'
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
      - ./config/tempo-data:/tmp/tempo
