definitions:
  custom.BadRequestError:
    properties:
      code:
        example: 400
        type: integer
      message:
        type: string
    type: object
  custom.Created:
    properties:
      code:
        example: 201
        type: integer
      message:
        example: Created
        type: string
    type: object
  custom.ExampleBodyPg:
    properties:
      class:
        type: string
      id:
        type: integer
      name:
        type: string
      rank:
        type: string
      tiersetpieces:
        type: integer
    required:
    - class
    - name
    - rank
    - tiersetpieces
    type: object
  custom.ExampleBodyUser:
    properties:
      battle_tag:
        type: string
      id:
        type: integer
      name:
        type: string
      surname:
        type: string
      username:
        type: string
    required:
    - battle_tag
    - name
    - surname
    - username
    type: object
  custom.InternalServerError:
    properties:
      code:
        example: 500
        type: integer
      message:
        type: string
    type: object
  custom.NotFoundError:
    properties:
      code:
        example: 404
        type: integer
      message:
        type: string
    type: object
  custom.Success:
    properties:
      code:
        example: 200
        type: integer
      message:
        example: Success
        type: string
    type: object
  models.Personaggio:
    properties:
      class:
        type: string
      id:
        type: integer
      name:
        type: string
      rank:
        type: string
      tiersetpieces:
        maximum: 4
        type: integer
      user_id:
        type: integer
      user_username:
        type: string
    required:
    - class
    - name
    - rank
    - tiersetpieces
    type: object
  models.User:
    properties:
      battle_tag:
        type: string
      id:
        type: integer
      name:
        type: string
      pg:
        $ref: '#/definitions/models.Personaggio'
      surname:
        type: string
      username:
        type: string
    required:
    - battle_tag
    - name
    - pg
    - surname
    - username
    type: object
info:
  contact: {}
paths:
  /guild/:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/custom.BadRequestError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/custom.NotFoundError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/custom.InternalServerError'
      summary: Get all users
      tags:
      - Guild
  /guild/{name}:
    get:
      description: Get all pg for user
      parameters:
      - description: name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/custom.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/custom.BadRequestError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/custom.NotFoundError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/custom.InternalServerError'
      summary: Get all pg for user
      tags:
      - Guild
  /guild/{username}:
    delete:
      parameters:
      - description: name
        in: path
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/custom.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/custom.BadRequestError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/custom.InternalServerError'
      tags:
      - Guild
  /guild/pg:
    post:
      description: Insert one pg
      parameters:
      - description: User
        in: body
        name: pg
        required: true
        schema:
          $ref: '#/definitions/custom.ExampleBodyPg'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/custom.Created'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/custom.BadRequestError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/custom.NotFoundError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/custom.InternalServerError'
      summary: Insert one pg
      tags:
      - Guild
  /guild/usr:
    post:
      consumes:
      - application/json
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/custom.ExampleBodyUser'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/custom.Created'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/custom.BadRequestError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/custom.NotFoundError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/custom.InternalServerError'
      summary: Insert one user
      tags:
      - Guild
swagger: "2.0"
